actor_dropout: 0.1
actor_lr: 0.0003
batch_size: 256
beta: 3.0
buffer_size: 1000000
checkpoints_path: null
reward_model_path: ~/CORL/pen_labels/mr_pen/best_model.ckpt
query_length: 1
dataset_id: D4RL/pen/expert-v2
eval_episodes: 10
eval_every: 5000
eval_seed: 0
gamma: 0.99
group: iql-pref-pen-expert-v1-multiseed-v0
iql_deterministic: false
iql_tau: 0.8
name: iql-p
normalize_reward: false
normalize_state: true
project: CORL
qf_lr: 0.0003
tau: 0.005
train_seed: 0
update_steps: 1000000
vf_lr: 0.0003