actor_dropout: 0.1
actor_lr: 0.0003
batch_size: 256
beta: 10.0
checkpoints_path: BB
dataset_id: bbway1
dataset_path: ~/CORL/t0012/reward_data_1/bbway1_t0012.hdf5
reward_model_path: ~/CORL/t0012/pt_rewards_1/best_model.ckpt
move_stats_path: ~/CORL/t0012/cache/p_stats.npy
eval_episodes: 100
eval_every: 5000
eval_seed: 0
gamma: 0.99
group: iql-bb
iql_deterministic: false
iql_tau: 0.9
name: iql
normalize_state: true
normalize_reward: true
project: CORL
qf_lr: 0.0003
tau: 0.005
train_seed: 0
update_steps: 1000000
vf_lr: 0.0003
